### ISSUE TITLE
Refactor Preference Helper to Kotlin

### ISSUE THREAD

**Issue by Tenkei** [Tenkei/Calendor#15]
Hi, this is a first timer issue, you only have to convert PreferenceHelper class to Kotlin and optimize it using Kotlin features.

You can check [here](https://gist.github.com/MarcDiethelm/7303312) and [here](https://github.com/firstcontributions/first-contributions) for step by step guide to make contribution.

**Comment by shbhmnk** [comment]
@Tenkei I would like to pick this up! Looks like a good place to start.

**Comment by Tenkei** [comment]
@shubh10 Great! Be sure to take a look at [contribution ](https://github.com/Tenkei/Calendor#contributing )section first. If you have any question I would be happy yo help.

Looking forward to your pull request (^^)

**Comment by shbhmnk** [comment]
Hey @Tenkei, checkout https://github.com/Tenkei/Calendor/pull/25 when you get a second. 
Please let me know if you need anything different in the changes.

**Comment by Tenkei** [comment]
Great Job!
